services:
  blogservice:
    image: ${DOCKER_REGISTRY-}blogservice
    build:
      context: .
      dockerfile: BlogService/Dockerfile
    depends_on:
     - cache
  
  cache:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
     - "6397:6397"